apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: 'spring-boot-services'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets:
              - 'api-gateway.robomart.svc.cluster.local:8080'
              - 'product-service.robomart.svc.cluster.local:8081'
              - 'cart-service.robomart.svc.cluster.local:8082'
              - 'order-service.robomart.svc.cluster.local:8083'
              - 'inventory-service.robomart.svc.cluster.local:8084'
              - 'payment-service.robomart.svc.cluster.local:8086'
              - 'notification-service.robomart.svc.cluster.local:8087'
