apiVersion: v1
kind: Service
metadata:
  name: inventory-service
  namespace: robomart
spec:
  selector:
    app: inventory-service
  ports:
  - port: 8084
    targetPort: 8084
    protocol: TCP
    name: http
  - port: 9094
    targetPort: 9094
    protocol: TCP
    name: grpc
  type: ClusterIP
