package com.robomart.order.contract;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.TestTemplate;
import org.junit.jupiter.api.extension.ExtendWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.web.server.LocalServerPort;
import org.springframework.context.annotation.Import;
import org.springframework.kafka.core.KafkaTemplate;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.test.context.bean.override.mockito.MockitoBean;

import au.com.dius.pact.provider.junit5.HttpTestTarget;
import au.com.dius.pact.provider.junit5.PactVerificationContext;
import au.com.dius.pact.provider.junit5.PactVerificationInvocationContextProvider;
import au.com.dius.pact.provider.junitsupport.Provider;
import au.com.dius.pact.provider.junitsupport.State;
import au.com.dius.pact.provider.junitsupport.loader.PactFolder;

import com.robomart.proto.inventory.InventoryServiceGrpc;
import com.robomart.proto.payment.PaymentServiceGrpc;
import com.robomart.test.PostgresContainerConfig;

/**
 * Pact provider test: verifies that Order Service satisfies the contract defined by
 * Notification Service consumer.
 *
 * Pact files are read from src/test/resources/pacts/ (committed to source control).
 * These pact files were generated by NotificationOrderConsumerPactTest.
 *
 * Seed data (R__seed_orders.sql) provides order 4 (CONFIRMED, user-002) and
 * ensures "order 99999 does not exist" by not inserting it.
 *
 * Build order: notification-service consumer tests run first (generate pacts),
 * then order-service provider tests verify. When using committed pact files,
 * order doesn't matter.
 */
@SpringBootTest(
        webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT,
        properties = "management.endpoint.health.validate-group-membership=false"
)
@ActiveProfiles("test")
@Import(PostgresContainerConfig.class)
@Provider("order-service")
@PactFolder("src/test/resources/pacts")
class OrderServicePactProviderIT {

    @LocalServerPort
    private int port;

    @MockitoBean
    private InventoryServiceGrpc.InventoryServiceBlockingStub inventoryStub;

    @MockitoBean
    private PaymentServiceGrpc.PaymentServiceBlockingStub paymentStub;

    @MockitoBean
    @SuppressWarnings("rawtypes")
    private KafkaTemplate kafkaTemplate;

    @Autowired
    private org.springframework.jdbc.core.JdbcTemplate jdbcTemplate;

    @BeforeEach
    void setUp(PactVerificationContext context) {
        context.setTarget(new HttpTestTarget("localhost", port));
    }

    @TestTemplate
    @ExtendWith(PactVerificationInvocationContextProvider.class)
    void pactVerificationTestTemplate(PactVerificationContext context) {
        context.verifyInteraction();
    }

    /**
     * Order 4 is already seeded by R__seed_orders.sql in the test profile.
     * Status: CONFIRMED, userId: user-002, totalAmount: 79.99.
     * No additional setup needed.
     */
    @State("order 4 exists in CONFIRMED status")
    void verifyOrder4Exists() {
        // Verify seed data is present — R__seed_orders.sql runs via Flyway on test startup
        Integer count = jdbcTemplate.queryForObject(
                "SELECT COUNT(*) FROM orders WHERE id = 4 AND status = 'CONFIRMED'",
                Integer.class);
        if (count == null || count == 0) {
            // Seed data not present — insert explicitly
            jdbcTemplate.update(
                    "INSERT INTO orders (id, user_id, total_amount, status, shipping_address, version) "
                    + "VALUES (4, 'user-002', 79.99, 'CONFIRMED', "
                    + "'{\"street\":\"456 Oak Ave\",\"city\":\"Los Angeles\",\"state\":\"CA\","
                    + "\"zip\":\"90001\",\"country\":\"US\"}', 0) "
                    + "ON CONFLICT (id) DO NOTHING");
        }
    }

    /**
     * Order 99999 must not exist — seed data does not include it.
     * This state ensures no record with that ID exists.
     */
    @State("order 99999 does not exist")
    void verifyOrder99999Missing() {
        jdbcTemplate.update("DELETE FROM order_items WHERE order_id = 99999");
        jdbcTemplate.update("DELETE FROM order_status_history WHERE order_id = 99999");
        jdbcTemplate.update("DELETE FROM outbox_events WHERE aggregate_id = '99999'");
        jdbcTemplate.update("DELETE FROM orders WHERE id = 99999");
    }
}
