package com.robomart.order.enums;

public enum OrderStatus {
    PENDING,
    PAYMENT_PENDING,
    INVENTORY_RESERVING,
    PAYMENT_PROCESSING,
    CONFIRMED,
    SHIPPED,
    DELIVERED,
    CANCELLED,
    PAYMENT_REFUNDING,
    INVENTORY_RELEASING
}
