spring:
  application:
    name: payment-service
  profiles:
    active: dev
  flyway:
    enabled: true
    locations: classpath:db/migration
  kafka:
    bootstrap-servers: localhost:29092
    properties:
      schema.registry.url: http://localhost:8085
  grpc:
    server:
      port: 9095

server:
  port: 8086

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:5436/payment_db
    username: robomart
    password: robomart
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  metrics:
    distribution:
      percentiles:
        "[http.server.requests]": 0.95

---
spring:
  config:
    activate:
      on-profile: demo
  flyway:
    locations: classpath:db/migration

---
spring:
  config:
    activate:
      on-profile: test
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    locations: classpath:db/migration
