apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: robomart
spec:
  selector:
    app: order-service
  ports:
  - port: 8083
    targetPort: 8083
    protocol: TCP
    name: http
  - port: 9093
    targetPort: 9093
    protocol: TCP
    name: grpc
  type: ClusterIP
