spring:
  application:
    name: product-service
  profiles:
    active: dev
  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: 8081

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/product_db
    username: robomart
    password: robomart
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

---
spring:
  config:
    activate:
      on-profile: demo
  flyway:
    locations: classpath:db/migration,classpath:db/seed

---
spring:
  config:
    activate:
      on-profile: test
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    locations: classpath:db/migration,classpath:db/seed
