apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yml
  - configmap.yml
  - ../services/api-gateway/deployment.yml
  - ../services/api-gateway/service.yml
  - ../services/api-gateway/hpa.yml
  - ../services/product-service/deployment.yml
  - ../services/product-service/service.yml
  - ../services/product-service/hpa.yml
  - ../services/cart-service/deployment.yml
  - ../services/cart-service/service.yml
  - ../services/cart-service/hpa.yml
  - ../services/order-service/deployment.yml
  - ../services/order-service/service.yml
  - ../services/order-service/hpa.yml
  - ../services/inventory-service/deployment.yml
  - ../services/inventory-service/service.yml
  - ../services/inventory-service/hpa.yml
  - ../services/payment-service/deployment.yml
  - ../services/payment-service/service.yml
  - ../services/payment-service/hpa.yml
  - ../services/notification-service/deployment.yml
  - ../services/notification-service/service.yml
  - ../services/notification-service/hpa.yml
