apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: robomart
spec:
  selector:
    app: payment-service
  ports:
  - port: 8086
    targetPort: 8086
    protocol: TCP
    name: http
  - port: 9095
    targetPort: 9095
    protocol: TCP
    name: grpc
  type: ClusterIP
