package com.robomart.product.contract;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.TestTemplate;
import org.junit.jupiter.api.extension.ExtendWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.web.server.LocalServerPort;
import org.springframework.jdbc.core.JdbcTemplate;

import au.com.dius.pact.provider.junit5.HttpTestTarget;
import au.com.dius.pact.provider.junit5.PactVerificationContext;
import au.com.dius.pact.provider.junit5.PactVerificationInvocationContextProvider;
import au.com.dius.pact.provider.junitsupport.Provider;
import au.com.dius.pact.provider.junitsupport.State;
import au.com.dius.pact.provider.junitsupport.loader.PactFolder;

import com.robomart.test.IntegrationTest;

/**
 * Pact provider test: verifies that Product Service satisfies the contract defined by
 * Notification Service consumer.
 *
 * Pact files are read from src/test/resources/pacts/ (committed to source control).
 * These pact files were generated by NotificationProductConsumerPactTest.
 *
 * Product 10 ("Smart Fitness Watch", ELEC-010, $179.99) is pre-seeded by
 * R__seed_products.sql in the test profile. No additional setup needed.
 *
 * Uses @IntegrationTest because Product Service requires Elasticsearch + Redis at startup.
 */
@IntegrationTest
@Provider("product-service")
@PactFolder("src/test/resources/pacts")
class ProductPactProviderIT {

    @LocalServerPort
    private int port;

    @Autowired
    private JdbcTemplate jdbcTemplate;

    @BeforeEach
    void setUp(PactVerificationContext context) {
        context.setTarget(new HttpTestTarget("localhost", port));
    }

    @TestTemplate
    @ExtendWith(PactVerificationInvocationContextProvider.class)
    void pactVerificationTestTemplate(PactVerificationContext context) {
        context.verifyInteraction();
    }

    /**
     * Product 10 is already seeded by R__seed_products.sql in the test profile:
     * (10, 'ELEC-010', 'Smart Fitness Watch', ..., 179.99, 1, ...).
     * No additional setup needed — just verify it's there.
     */
    @State("product 10 exists")
    void verifyProduct10Exists() {
        int count = jdbcTemplate.queryForObject(
                "SELECT COUNT(*) FROM products WHERE id = 10",
                Integer.class);
        if (count == 0) {
            // Seed data not present — insert explicitly
            jdbcTemplate.update(
                    "INSERT INTO products (id, sku, name, description, price, category_id, "
                    + "rating, brand, stock_quantity, version, active) "
                    + "VALUES (10, 'ELEC-010', 'Smart Fitness Watch', "
                    + "'GPS fitness watch with 14-day battery life.', "
                    + "179.99, 1, 4.30, 'FitPulse', 200, 0, true) "
                    + "ON CONFLICT (id) DO NOTHING");
        }
    }
}
