package com.robomart.common.logging;

public enum ErrorCode {
    RESOURCE_NOT_FOUND,
    PRODUCT_NOT_FOUND,
    BUSINESS_RULE_VIOLATION,
    VALIDATION_ERROR,
    CART_NOT_FOUND,
    CART_ITEM_NOT_FOUND,
    CART_EXPIRED,
    EXTERNAL_SERVICE_ERROR,
    INTERNAL_ERROR,
    ORDER_NOT_CANCELLABLE
}
